controller_manager:
  ros__parameters:
    update_rate: 50 # Hz
    use_sim_time: true # 8014595719 #263

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


ackermann_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: false

    rear_wheels_names: [rear_right_wheel_joint,rear_left_wheel_joint]
    front_wheels_names: [front_left_steer_joint,front_right_steer_joint]
    virtual_front_wheels: [front_left_wheel_joint, front_right_wheel_joint]

    wheelbase: 0.2 # Distance between center of back wheels and front wheel
    front_wheel_track: 0.155
    rear_wheel_track: 0.155
    front_wheels_radius: 0.05 # Radius of front wheel
    rear_wheels_radius: 0.05

# http://wiki.ros.org/ackermann_steering_controller
# https://github.com/ros-controls/ros2_controllers/blob/master/ackermann_steering_controller/test/ackermann_steering_controller_params.yaml